name: absen_qr_fix
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  audioplayers: ^6.5.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  get: ^4.7.3
  google_fonts: ^6.3.2
  intl: ^0.20.2
  just_audio: ^0.10.5
  mobile_scanner: ^7.1.3
  permission_handler: ^12.0.1
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/ding.mp3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
